### ISSUE TITLE
Error authorizing app

### ISSUE THREAD

**Issue by seannymurrs** [AndrewLester/update-scheduler#11]
I get the following error when trying to authorize the app.

`Unable to authenticate, there was no valid return URL found. Please report this to your administrator.`

**Comment by AndrewLester** [comment]
Thanks for reporting this! It looks like Schoology recently made a change to their authorization flow to prevent redirects back to URLs without SSL. As a temporary fix, try using this URL for the site (HTTPS is important):
https://www.updatescheduler.com/

I will push out an update later to redirect HTTP -> HTTPS.

**Comment by AndrewLester** [comment]
Update is live. All URLs are redirected to HTTPS and old site URLs are redirected to the new one.
