### ISSUE TITLE
Support embedded media in updates

### ISSUE THREAD

**Issue by AndrewLester** [AndrewLester/update-scheduler#12]
Support embedded media in updates (iframes for now) using quillJS https://quilljs.com/guides/cloning-medium-with-parchment/

**Comment by AndrewLester** [comment]
"Video" toolbar action added.

**Comment by mrhladio** [comment]
This is a helpful upgrade! Could embedded content from sites, (not just video) be optimized? I'm specifically thinking about our principals who create newsletters using Smore.

**Comment by AndrewLester** [comment]
Yes, great question! Currently, the system *does* support embedded content from any site, despite the very confusing language and icon. To include the embedded content from another site, you'll just need to put the site's URL (not embed code) into the "Enter video:" input box. Here's an example:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/23221268/198507542-67cd9d3c-ff13-4ab0-9573-11af9ed8ce44.png">

To be clear, this is both confusing and not entirely feature complete. I plan to reword the input box, change the icon, and allow you to resize such embedded content. I ran into an issue earlier with a resizing library that may mean I'll need to reimplement it, which will take some time. I'll track these additional features in a new issue, but I wanted to try getting a minimal solution out sooner rather than later. Sorry about the confusion!
